{% set name = "mxtools" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mxtools-{{ version }}.tar.gz
  sha256: 6421da96419da2c9d2e4d6a9ddcd9e732850375316177e77c718e7b43a8883e3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - bluesky
    - ophyd
    - pyepics
    - tiled
    # TODO: remove tiled once databroker has tiled as a dependency for
    # databroker > 2.0.0b4

test:
  imports:
    - mxtools
    - mxtools.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NSLS-II-AMX/mxtools
  summary: Common code for the MX beamlines at NSLS-II (AMX, FMX).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vshekar
    - JunAishima
    - mrakitin
